[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[env]
  PORT = "8000"
  PYTHONPATH = "/app"